import {cp,mkdir,rm,writeFile} from "node:fs/promises";
import {dirname,join} from "node:path";
import {fileURLToPath} from "node:url";
import {articles} from "../content/articles.mjs";

const root=join(dirname(fileURLToPath(import.meta.url)),".."),out=join(root,"dist");
const repo="gateway-qualifications-entry-level-award-in-esol-skills-for-life-reading-web",base=`/${repo}`,origin=`https://mcyj.github.io/${repo}`,checkedAt="2026-09-19";
const appStoreUrl="https://apps.apple.com/gb/app/gq-esol-reading-e2/id6801917236";
const qualificationUrl="https://www.gatewayqualifications.org.uk/qualification/gateway-qualifications-entry-level-award-esol-skills-life-reading-entry-2/";
const specificationUrl="https://www.gatewayqualifications.org.uk/wp-content/uploads/2024/02/Qualification-Specification-ESOL-Skills-for-Life-E1-L2.pdf";
const sampleUrl="https://www.gatewayqualifications.org.uk/wp-content/uploads/2022/02/ESOL-Reading-E2-Assessor-Pack-Sample-2.pdf";
const esolUrl="https://www.gatewayqualifications.org.uk/qualification-area/esol/esol-entry-level-2/",email="june1012june@gmail.com";
const x=v=>String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
async function put(path,value){const target=join(out,path);await mkdir(dirname(target),{recursive:true});await writeFile(target,value)}
const t={html:"en-GB",nav:["Study guides","FAQ","Support"],home:"Home",guides:"Study guides",faq:"Frequently asked questions",privacy:"Privacy Policy",terms:"Terms of Use",support:"Support",contact:"Contact",skip:"Skip to content",reviewed:"Official sources checked",official:"Official sources",related:"Read next",store:"Get the app",coming:"Google Play · Coming soon",tagline:"Read the clue. Find the answer.",independent:"Independent study support by RushLabs. Not affiliated with, approved by or endorsed by Gateway Qualifications.",current:"Assessment papers, centre arrangements, fees and qualification documents can change. Current Gateway Qualifications and approved-centre instructions always control."};
const c={eyebrow:"ESOL SKILLS FOR LIFE · READING · ENTRY 2",hero:"Everyday English.",accent:"Read with purpose.",lede:"Build confidence with 500 independently written reading tasks across signs, forms, instructions, messages, vocabulary, meaning, detail and inference.",level:"LEVEL",levelValue:"Entry Level 2",levelNote:"Qualification 601/5416/0",format:"ASSESSMENT",formatValue:"4 reading tasks",formatNote:"One hour · supervised",unit:"UNIT",unitValue:"6 credits · 60 GLH",unitNote:"M/506/8491 Reading Entry 2",inside:"Inside the app",insideTitle:"Practise the reading you use in real life",insideText:"Work through ten chapters, mock assessments, clear explanations, mistake review and offline progress without a RushLabs account.",method:"A simple reading routine",methodTitle:"Purpose → clue → evidence → answer",methodText:"Start with what the text is for, locate the words that matter, prove the meaning with evidence and then choose the answer. This keeps unfamiliar vocabulary from controlling the whole task.",all:"Browse all 12 guides",intro:"Clear Entry 2 reading guides grounded in the current Gateway qualification page, specification and sample assessor guidance.",sourceLead:"Use these guides for independent practice. Your approved centre and Gateway Qualifications control assessment delivery, contextualisation, reasonable adjustments and results.",appAside:"Continue with 500 original questions, mock sets, explanations and local progress in the app.",faqLead:"Clear answers about the Award, four-task format, timing, dictionary use, grading, centres and app boundaries.",legalDate:"Effective September 19, 2026"};
function nav(){return `<header class="site-header"><a class="brand" href="${base}/en/"><img src="${base}/assets/app-icon.png" width="46" height="46" alt=""><span>ESOL READING<br><strong>ENTRY 2</strong></span></a><nav aria-label="Primary"><a href="${base}/en/guides/">${t.nav[0]}</a><a href="${base}/en/faq/">${t.nav[1]}</a><a href="${base}/en/support/">${t.nav[2]}</a></nav></header>`}
function footer(){return `<footer><div><strong>GQ ESOL Reading E2</strong><p>${t.independent}</p></div><nav aria-label="Legal"><a href="${base}/en/privacy/">${t.privacy}</a><a href="${base}/en/terms/">${t.terms}</a><a href="${base}/en/support/">${t.support}</a><a href="${base}/en/contact/">${t.contact}</a></nav><p class="source-note">${t.current} · ${checkedAt}</p></footer>`}
function layout({title,description,path="",body,type="website",schema=null}){const url=`${origin}/en/${path}`;return `<!doctype html><html lang="${t.html}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${x(title)}</title><meta name="description" content="${x(description)}"><link rel="canonical" href="${url}"><link rel="alternate" hreflang="en-GB" href="${url}"><link rel="alternate" hreflang="x-default" href="${url}"><meta property="og:type" content="${type}"><meta property="og:title" content="${x(title)}"><meta property="og:description" content="${x(description)}"><meta property="og:url" content="${url}"><meta property="og:site_name" content="GQ ESOL Reading E2"><meta name="twitter:card" content="summary"><meta name="theme-color" content="#1837b8"><link rel="icon" href="${base}/assets/app-icon.png"><link rel="stylesheet" href="${base}/assets/styles.css">${schema?`<script type="application/ld+json">${JSON.stringify(schema).replaceAll("<","\\u003c")}</script>`:""}</head><body><a class="skip" href="#main">${t.skip}</a><div class="page-shell">${nav()}<main id="main">${body}</main>${footer()}</div></body></html>`}
function stores(){return `<div class="store-block"><p class="eyebrow">${t.store}</p><div class="store-row store-badge-frame-sync"><a class="store-link" href="${appStoreUrl}" aria-label="Download on the App Store"><img src="${base}/assets/app-store-badge.svg" width="194" height="75" alt="Download on the App Store"></a><span class="store-disabled" aria-label="${t.coming}"><span aria-hidden="true">▶</span>${t.coming}</span></div></div>`}
function official(){return `<aside class="official-source"><h2>${t.official}</h2><p>${c.sourceLead}</p><div><a href="${qualificationUrl}">Entry 2 Reading qualification page</a><a href="${specificationUrl}">ESOL Skills for Life specification</a><a href="${sampleUrl}">Reading Entry 2 sample assessor pack</a><a href="${esolUrl}">ESOL Entry Level 2 overview</a></div></aside>`}
const routine=[["01","PURPOSE"],["02","CLUE"],["03","EVIDENCE"],["04","ANSWER"]];
function home(){return `<section class="hero"><div class="hero-copy"><p class="eyebrow">${c.eyebrow}</p><h1>${c.hero}<br><span>${c.accent}</span></h1><p class="lede">${c.lede}</p>${stores()}</div><div class="fact-stack"><article><b>${c.level}</b><strong>${c.levelValue}</strong><span>${c.levelNote}</span></article><article><b>${c.format}</b><strong>${c.formatValue}</strong><span>${c.formatNote}</span></article><article><b>${c.unit}</b><strong>${c.unitValue}</strong><span>${c.unitNote}</span></article></div><figure class="phone-stage"><img src="${base}/assets/screenshots/home.png" width="1019" height="2208" alt="GQ ESOL Reading E2 home screen"></figure></section><section class="marker-strip">${routine.map(([n,v])=>`<span><b>${n}</b>${v}</span>`).join("")}</section><section class="section method"><div><p class="eyebrow">${c.method}</p><h2>${c.methodTitle}</h2><p>${c.methodText}</p><a class="text-link" href="${base}/en/guides/text-purpose-and-layout/">${articles[2].title} →</a></div><div class="worksheet">${routine.map(([n,v])=>`<div><b>${n}</b><span>${v}</span><i></i></div>`).join("")}</div></section><section class="section app-preview"><div class="section-heading"><div><p class="eyebrow">${c.inside}</p><h2>${c.insideTitle}</h2></div><p>${c.insideText}</p></div><div class="screens"><figure><img loading="lazy" src="${base}/assets/screenshots/practice.png" width="1019" height="2208" alt="Entry 2 reading practice"><figcaption>Focused reading practice</figcaption></figure><figure><img loading="lazy" src="${base}/assets/screenshots/explanation.png" width="1019" height="2208" alt="Answer explanation"><figcaption>Clear answer explanations</figcaption></figure><figure><img loading="lazy" src="${base}/assets/screenshots/mock.png" width="1019" height="2208" alt="Mock assessments"><figcaption>Mock assessment rhythm</figcaption></figure></div></section><section class="section guide-preview"><div class="section-heading"><div><p class="eyebrow">${t.guides}</p><h2>${c.intro}</h2></div><a class="text-link" href="${base}/en/guides/">${c.all} →</a></div><div class="guide-grid">${articles.slice(0,6).map((v,i)=>`<a class="guide-card" href="${base}/en/guides/${v.slug}/"><span>${String(i+1).padStart(2,"0")} · ${v.category}</span><h3>${v.title}</h3><p>${v.description}</p></a>`).join("")}</div></section><section class="final-cta"><p class="eyebrow">${c.eyebrow}</p><h2>${t.tagline}</h2>${stores()}</section>`}
function articlePage(a){const i=articles.findIndex(v=>v.slug===a.slug),related=[articles[(i+1)%articles.length],articles[(i+4)%articles.length]];const body=`<article class="article"><nav class="breadcrumbs"><a href="${base}/en/">${t.home}</a><span>/</span><a href="${base}/en/guides/">${t.guides}</a><span>/</span><span>${a.category}</span></nav><header><p class="eyebrow">${a.category}</p><h1>${a.title}</h1><p class="lede">${a.description}</p><p class="article-meta">${t.reviewed}: ${checkedAt}</p></header><div class="article-layout"><div class="article-copy">${a.sections.map(([h,p],n)=>`${n===2?`<div class="mini-routine">${routine.map(([num,v])=>`<span><b>${num}</b>${v}</span>`).join("")}</div>`:""}<section><h2>${h}</h2><p>${p}</p></section>`).join("")}${official()}</div><aside class="article-aside"><img src="${base}/assets/app-icon.png" width="88" height="88" alt="App icon"><h2>${t.store}</h2><p>${c.appAside}</p>${stores()}</aside></div><section class="related"><p class="eyebrow">${t.related}</p><div class="guide-grid">${related.map(v=>`<a class="guide-card" href="${base}/en/guides/${v.slug}/"><span>${v.category}</span><h3>${v.title}</h3></a>`).join("")}</div></section></article>`;return layout({title:`${a.title} | GQ ESOL Reading E2`,description:a.description,path:`guides/${a.slug}/`,body,type:"article",schema:{"@context":"https://schema.org","@type":"Article",headline:a.title,description:a.description,datePublished:checkedAt,dateModified:checkedAt,inLanguage:t.html,author:{"@type":"Organization",name:"RushLabs"},publisher:{"@type":"Organization",name:"RushLabs"},mainEntityOfPage:`${origin}/en/guides/${a.slug}/`}})}
const faqs=[["Is this an official Gateway Qualifications app?","No. RushLabs developed it independently. It is not affiliated with, approved by or endorsed by Gateway Qualifications."],["What is the exact qualification number?","The Entry Level 2 Reading Award is 601/5416/0 and its mandatory unit is M/506/8491 Reading Entry 2."],["How is the qualification graded?","The current qualification page lists Pass grading and task-based controlled assessment."],["How many tasks are in the reading assessment?","The current sample assessor pack contains four supervised reading tasks."],["How much time is allowed?","The sample pack allocates one hour in total, with 15 minutes as the guide time for each of four tasks."],["Can I use a dictionary?","The current sample guidance allows a monolingual simplified dictionary or glossary. Follow your centre's current instructions."],["Must all tasks be completed together?","No. The sample guidance permits different sessions, but all four tasks are required and assessment materials cannot be taken away."],["Are prior qualifications required?","The current qualification page says no prior qualification or specific attainment level is required, while centres should use initial or diagnostic assessment to confirm suitability."],["Does the app use official assessment questions?","No. Its 500 tasks and explanations are independently written."],["Which Store is available?","The exact App Store app ID is public. No public Google Play listing was found for the exact package on September 19, 2026."],["Does the app issue a qualification?","No. Only an approved assessment process can lead to the qualification."],["Is an account required?","No RushLabs account is required. Study records are stored on the device."]];
const legal={privacy:[["App and study data","The app requires no RushLabs account. Answers, progress, saved items, notes and settings are stored on the device."],["Purchases","Apple processes purchases under its terms. This website collects no payment information."],["Website","This static website uses no analytics, advertising cookies, accounts or contact forms."]],terms:[["Independent study aid","This is not an official Gateway Qualifications product and does not contain official assessment items."],["No guarantee or qualification","Practice results do not guarantee a pass and the app does not issue a qualification."],["Official arrangements control","Gateway Qualifications and the approved centre control assessment delivery, reasonable adjustments, fees and results."]],support:"Include the product name, device, operating system, app version and steps to reproduce the issue.",private:"Do not send passwords, payment information, receipts, purchase tokens, assessment papers or sensitive learner records."};

await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});await cp(join(root,"assets"),join(out,"assets"),{recursive:true});await cp(join(root,"styles.css"),join(out,"assets","styles.css"));await cp(join(root,".nojekyll"),join(out,".nojekyll"));
await put("index.html",`<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GQ ESOL Reading E2</title><meta name="description" content="Independent ESOL Reading Entry 2 study guides and practice app."><link rel="canonical" href="${origin}/en/"><meta http-equiv="refresh" content="0;url=./en/"><script>location.replace('./en/')</script></head><body><main id="main"><a href="./en/">GQ ESOL Reading E2</a></main></body></html>`);
const urls=[];async function add(path,html){urls.push(`/en/${path}`);await put(`en/${path}index.html`,html)}
await add("",layout({title:`GQ ESOL Reading E2 | ${t.tagline}`,description:c.lede,body:home(),schema:{"@context":"https://schema.org","@type":"SoftwareApplication",name:"GQ ESOL Reading E2",identifier:"app.mcyj.examprep.glb2464",applicationCategory:"EducationalApplication",operatingSystem:"iOS",description:c.insideText,url:`${origin}/en/`,downloadUrl:appStoreUrl,publisher:{"@type":"Organization",name:"RushLabs"}}}));
await add("guides/",layout({title:`${t.guides} | GQ ESOL Reading E2`,description:c.intro,path:"guides/",body:`<section class="page-intro"><p class="eyebrow">${t.guides}</p><h1>${t.guides}</h1><p>${c.intro}</p></section><section class="guide-grid all-guides">${articles.map(v=>`<a class="guide-card" href="${base}/en/guides/${v.slug}/"><span>${v.category}</span><h2>${v.title}</h2><p>${v.description}</p></a>`).join("")}</section>${official()}`}));for(const item of articles)await add(`guides/${item.slug}/`,articlePage(item));
await add("faq/",layout({title:`${t.faq} | GQ ESOL Reading E2`,description:c.faqLead,path:"faq/",body:`<section class="page-intro"><p class="eyebrow">FAQ</p><h1>${t.faq}</h1><p>${c.faqLead}</p></section><section class="faq-list">${faqs.map(([q,ans])=>`<details><summary>${q}</summary><p>${ans}</p></details>`).join("")}</section>${official()}`,schema:{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))}}));
await add("privacy/",layout({title:`${t.privacy} | GQ ESOL Reading E2`,description:`${t.privacy} — RushLabs.`,path:"privacy/",body:`<article class="policy"><p class="eyebrow">Legal</p><h1>${t.privacy}</h1><p class="article-meta">${c.legalDate}</p><h2>RushLabs</h2><p>${t.independent}</p>${legal.privacy.map(([h,p])=>`<h2>${h}</h2><p>${p}</p>`).join("")}<h2>${t.contact}</h2><p><a href="mailto:${email}">${email}</a>. ${legal.private}</p></article>`}));
await add("terms/",layout({title:`${t.terms} | GQ ESOL Reading E2`,description:`${t.terms} — RushLabs.`,path:"terms/",body:`<article class="policy"><p class="eyebrow">Legal</p><h1>${t.terms}</h1><p class="article-meta">${c.legalDate}</p>${legal.terms.map(([h,p])=>`<h2>${h}</h2><p>${p}</p>`).join("")}<h2>${t.contact}</h2><p><a href="mailto:${email}">${email}</a>.</p></article>`}));
await add("support/",layout({title:`${t.support} | GQ ESOL Reading E2`,description:`${t.support} — RushLabs.`,path:"support/",body:`<section class="page-intro"><p class="eyebrow">${t.support}</p><h1>${t.support}</h1><p>${legal.support}</p><a class="primary-button" href="mailto:${email}?subject=GQ%20ESOL%20Reading%20E2%20support">${email}</a></section><section class="support-grid"><div><h2>${t.store}</h2>${stores()}</div><div><h2>${t.official}</h2><p>${c.sourceLead}</p></div><div><h2>Private information</h2><p>${legal.private}</p></div></section>`}));
await add("contact/",layout({title:`${t.contact} | GQ ESOL Reading E2`,description:`${t.contact} — RushLabs.`,path:"contact/",body:`<section class="page-intro contact"><p class="eyebrow">${t.contact}</p><h1>RushLabs</h1><p>${t.independent}</p><a class="contact-email" href="mailto:${email}">${email}</a><p class="source-note">${legal.private}</p></section>`}));
await put("404.html",layout({title:"Page not found | GQ ESOL Reading E2",description:"The requested page could not be found.",path:"404.html",body:`<section class="page-intro"><p class="eyebrow">404</p><h1>This page is not in the workbook.</h1><a class="primary-button" href="${base}/en/">Return home</a></section>`}));
await put("sitemap.xml",`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u=>`  <url><loc>${origin}${u}</loc><lastmod>${checkedAt}</lastmod></url>`).join("\n")}\n</urlset>\n`);await put("robots.txt",`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);console.log(`Built ${urls.length} indexable pages in ${out}`);
